version: 2.1

orbs:
  node: circleci/node@4.7
  coveralls: coveralls/coveralls@2.1.1

workflows:
  sample:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
          parallelism: 4
          working_directory: ~/repo
          steps:
            - checkout
            - node/with-cache:
                steps:
                  - node/install-packages
                  - run:
                      name: Run tests with coverage
                      command: npm run test -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

      - coveralls/upload:
          requires:
            - node/test
          github-token: $GITHUB_TOKEN
