# .github/workflows/deploy.yml
name: Deploy to Cloud Run
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - run: cd frontend; npm install; cd ..

      - run: cd frontend; npm run build; cd ..

      #- commands for react
      # - run: cd frontend; cd react-frontend; npm install; cd ..; cd ..

      # - run: cd frontend; cd react-frontend; npm run build; cd ..; cd ..

      - run: npm start &

      #- run: npm run test-association-stats && npm run test-phone-line-stats && npm run test-projection-homes-stats
      
      - run: npm test
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
    
      - name: Deploy
        run: gcloud app deploy

